### ISSUE TITLE
Installation and operational issues

### ISSUE THREAD

**Issue by Jbarrers9740** [menta78/alphaBetaLab#3]
I clone the repository and I am finding errore when running the integrity test, and also when running an example code.

This is what I have done (in Anaconda console):

```
git clone https://github.com/menta78/alphaBetaLab.git
cd alphaBetaLab
python -m unittest test.testAbIntegrity
```

And this is the output. It seems to be an error with the variable alphaMtx:

```
C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py:43: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
  self.centroids = [c.centroid.coords[0] for c in cells]
C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py:46: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
  self.cellMap = dict(zip(self.cellCoordinates, cells))
C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py:47: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
  self.cellSfc = [c.area for c in cells]
C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py:48: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
  self.cellBnd = [tuple(c.boundary.coords[:]) for c in cells]
C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py:203: ShapelyDeprecationWarning: __len__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Check the length of the `geoms` property instead to get the  number of parts of a multi-part geometry.
  ncell = len(cells)
    initializing parallel environment ..
      ... done
C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py:208: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
  isLandOrCoastalCellGen = pl.imap(_cellIsOnLandOrCoastal, zip(cells, cellBnd, cellSfc, range(ncell)))
E    initializing parallel environment ..
D:\Programas\Entornos\general\lib\multiprocessing\pool.py:265: ResourceWarning: unclosed running multiprocessing pool <multiprocessing.pool.Pool state=RUN pool_size=4>
  _warn(f"unclosed running multiprocessing pool {self!r}",
ResourceWarning: Enable tracemalloc to get the object allocation traceback
      ... done
E    initializing parallel environment ..
      ... done
E    initializing parallel environment ..
      ... done
E    initializing parallel environment ..
      ... done
E    initializing parallel environment ..
      ... done
E
======================================================================
ERROR: testSyntheticCase01_parallel (test.testAbIntegrity.testIntegrity)
----------------------------------------------------------------------
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\Programas\Entornos\general\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py", line 233, in _cellIsOnLandOrCoastal
    cellAlphaMtx = alphaMtx.getAlphaSubMatrix(cell)
NameError: name 'alphaMtx' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gorgo\alphaBetaLab\test\testAbIntegrity.py", line 133, in testSyntheticCase01_parallel
    self._testSyntheticCase01(4)
  File "C:\Users\gorgo\alphaBetaLab\test\testAbIntegrity.py", line 123, in _testSyntheticCase01
    grid = rectGridBuilder.buildGrid(hrmtx, cstClDet)
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abRectangularGridBuilder.py", line 48, in buildGrid
    grd = abGrid.getSeaGrid(cells, crds, hiResAlphaMtx, coastalCellDetector,
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py", line 16, in getSeaGrid
    seaGrid = grd.removeLandAndCoastalCells(highResAlphaMtx, coastalCellDetector)
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py", line 214, in removeLandAndCoastalCells
    for isLandOrCoastal, icell in isLandOrCoastalCellGen:
  File "D:\Programas\Entornos\general\lib\multiprocessing\pool.py", line 870, in next
    raise value
NameError: name 'alphaMtx' is not defined

======================================================================
ERROR: testSyntheticCase01_serial (test.testAbIntegrity.testIntegrity)
----------------------------------------------------------------------
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\Programas\Entornos\general\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py", line 233, in _cellIsOnLandOrCoastal
    cellAlphaMtx = alphaMtx.getAlphaSubMatrix(cell)
NameError: name 'alphaMtx' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gorgo\alphaBetaLab\test\testAbIntegrity.py", line 130, in testSyntheticCase01_serial
    self._testSyntheticCase01(1)
  File "C:\Users\gorgo\alphaBetaLab\test\testAbIntegrity.py", line 123, in _testSyntheticCase01
    grid = rectGridBuilder.buildGrid(hrmtx, cstClDet)
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abRectangularGridBuilder.py", line 48, in buildGrid
    grd = abGrid.getSeaGrid(cells, crds, hiResAlphaMtx, coastalCellDetector,
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py", line 16, in getSeaGrid
    seaGrid = grd.removeLandAndCoastalCells(highResAlphaMtx, coastalCellDetector)
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py", line 214, in removeLandAndCoastalCells
    for isLandOrCoastal, icell in isLandOrCoastalCellGen:
  File "D:\Programas\Entornos\general\lib\multiprocessing\pool.py", line 870, in next
    raise value
NameError: name 'alphaMtx' is not defined

======================================================================
ERROR: testSyntheticCase04_parallel (test.testAbIntegrity.testIntegrity)
----------------------------------------------------------------------
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\Programas\Entornos\general\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py", line 233, in _cellIsOnLandOrCoastal
    cellAlphaMtx = alphaMtx.getAlphaSubMatrix(cell)
NameError: name 'alphaMtx' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gorgo\alphaBetaLab\test\testAbIntegrity.py", line 193, in testSyntheticCase04_parallel
    self._testSyntheticCase04(4)
  File "C:\Users\gorgo\alphaBetaLab\test\testAbIntegrity.py", line 183, in _testSyntheticCase04
    grid = rectGridBuilder.buildGrid(hrmtx, cstClDet)
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abRectangularGridBuilder.py", line 48, in buildGrid
    grd = abGrid.getSeaGrid(cells, crds, hiResAlphaMtx, coastalCellDetector,
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py", line 16, in getSeaGrid
    seaGrid = grd.removeLandAndCoastalCells(highResAlphaMtx, coastalCellDetector)
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py", line 214, in removeLandAndCoastalCells
    for isLandOrCoastal, icell in isLandOrCoastalCellGen:
  File "D:\Programas\Entornos\general\lib\multiprocessing\pool.py", line 870, in next
    raise value
NameError: name 'alphaMtx' is not defined

======================================================================
ERROR: testSyntheticCase04_serial (test.testAbIntegrity.testIntegrity)
----------------------------------------------------------------------
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\Programas\Entornos\general\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py", line 233, in _cellIsOnLandOrCoastal
    cellAlphaMtx = alphaMtx.getAlphaSubMatrix(cell)
NameError: name 'alphaMtx' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gorgo\alphaBetaLab\test\testAbIntegrity.py", line 190, in testSyntheticCase04_serial
    self._testSyntheticCase04(1)
  File "C:\Users\gorgo\alphaBetaLab\test\testAbIntegrity.py", line 183, in _testSyntheticCase04
    grid = rectGridBuilder.buildGrid(hrmtx, cstClDet)
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abRectangularGridBuilder.py", line 48, in buildGrid
    grd = abGrid.getSeaGrid(cells, crds, hiResAlphaMtx, coastalCellDetector,
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py", line 16, in getSeaGrid
    seaGrid = grd.removeLandAndCoastalCells(highResAlphaMtx, coastalCellDetector)
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py", line 214, in removeLandAndCoastalCells
    for isLandOrCoastal, icell in isLandOrCoastalCellGen:
  File "D:\Programas\Entornos\general\lib\multiprocessing\pool.py", line 870, in next
    raise value
NameError: name 'alphaMtx' is not defined

======================================================================
ERROR: testSyntheticCase07_totalBlock_parallel (test.testAbIntegrity.testIntegrity)
----------------------------------------------------------------------
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\Programas\Entornos\general\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py", line 233, in _cellIsOnLandOrCoastal
    cellAlphaMtx = alphaMtx.getAlphaSubMatrix(cell)
NameError: name 'alphaMtx' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gorgo\alphaBetaLab\test\testAbIntegrity.py", line 242, in testSyntheticCase07_totalBlock_parallel
    self._testSyntheticCase07_totalBlock(4)
  File "C:\Users\gorgo\alphaBetaLab\test\testAbIntegrity.py", line 232, in _testSyntheticCase07_totalBlock
    grid = rectGridBuilder.buildGrid(hrmtx, cstClDet)
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abRectangularGridBuilder.py", line 48, in buildGrid
    grd = abGrid.getSeaGrid(cells, crds, hiResAlphaMtx, coastalCellDetector,
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py", line 16, in getSeaGrid
    seaGrid = grd.removeLandAndCoastalCells(highResAlphaMtx, coastalCellDetector)
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py", line 214, in removeLandAndCoastalCells
    for isLandOrCoastal, icell in isLandOrCoastalCellGen:
  File "D:\Programas\Entornos\general\lib\multiprocessing\pool.py", line 870, in next
    raise value
NameError: name 'alphaMtx' is not defined

======================================================================
ERROR: testSyntheticCase07_totalBlock_serial (test.testAbIntegrity.testIntegrity)
----------------------------------------------------------------------
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\Programas\Entornos\general\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py", line 233, in _cellIsOnLandOrCoastal
    cellAlphaMtx = alphaMtx.getAlphaSubMatrix(cell)
NameError: name 'alphaMtx' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gorgo\alphaBetaLab\test\testAbIntegrity.py", line 239, in testSyntheticCase07_totalBlock_serial
    self._testSyntheticCase07_totalBlock(1)
  File "C:\Users\gorgo\alphaBetaLab\test\testAbIntegrity.py", line 232, in _testSyntheticCase07_totalBlock
    grid = rectGridBuilder.buildGrid(hrmtx, cstClDet)
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abRectangularGridBuilder.py", line 48, in buildGrid
    grd = abGrid.getSeaGrid(cells, crds, hiResAlphaMtx, coastalCellDetector,
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py", line 16, in getSeaGrid
    seaGrid = grd.removeLandAndCoastalCells(highResAlphaMtx, coastalCellDetector)
  File "C:\Users\gorgo\alphaBetaLab\alphaBetaLab\abGrid.py", line 214, in removeLandAndCoastalCells
    for isLandOrCoastal, icell in isLandOrCoastalCellGen:
  File "D:\Programas\Entornos\general\lib\multiprocessing\pool.py", line 870, in next
    raise value
NameError: name 'alphaMtx' is not defined

----------------------------------------------------------------------
Ran 6 tests in 17.491s

FAILED (errors=6)
```

After that, I tried an installation by using the next code and everything seems to be working correctly:

`python setup.py install`

This is the output:

```
running install
D:\Programas\Entornos\general\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
D:\Programas\Entornos\general\lib\site-packages\setuptools\command\easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing manifest file 'alphaBetaLab.egg-info\SOURCES.txt'
running install_lib
running build_py
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\alphaBetaLab
creating build\bdist.win-amd64\egg\alphaBetaLab\plot
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abAlphaBetaRecalibrator.py to abAlphaBetaRecalibrator.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abBathyDataGridder.py to abBathyDataGridder.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abCellsEstimator.py to abCellsEstimator.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abCellsEstimatorParallel.py to abCellsEstimatorParallel.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abCellSize.py to abCellSize.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abCoastalCellDetector.py to abCoastalCellDetector.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abEstimateAndSave.py to abEstimateAndSave.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abEtopo1BathyLoader.py to abEtopo1BathyLoader.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abFirstOctantTransformation.py to abFirstOctantTransformation.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abFixBasemap.py to abFixBasemap.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abGebcoBathyLoader.py to abGebcoBathyLoader.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abGrid.py to abGrid.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abHighResAlphaMatrix.py to abHighResAlphaMatrix.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abLongBreakWaterLocAlphaAdjust.py to abLongBreakWaterLocAlphaAdjust.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abOptionManager.py to abOptionManager.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abRectangularGridBuilder.py to abRectangularGridBuilder.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abSingleCellAlphaEstimator.py to abSingleCellAlphaEstimator.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abSingleCellBetaEstimator.py to abSingleCellBetaEstimator.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abTriangularMesh.py to abTriangularMesh.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abTriangularMeshGridBuilder.py to abTriangularMeshGridBuilder.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abUpstreamPolyEstimator.py to abUpstreamPolyEstimator.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abUtils.py to abUtils.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abWwiiiAlphaBetaLoader.py to abWwiiiAlphaBetaLoader.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abWwiiiGridFilesCompiler.py to abWwiiiGridFilesCompiler.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abWwiiiObstrFileSaver.py to abWwiiiObstrFileSaver.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\abWwiiiPropSchObstrFileSaver.py to abWwiiiPropSchObstrFileSaver.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\plot\abAlphaBetaPlotter.py to abAlphaBetaPlotter.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\plot\abHighResAlphaMatrixPlot.py to abHighResAlphaMatrixPlot.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\plot\abPolyPlot.py to abPolyPlot.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\plot\__init__.py to __init__.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\alphaBetaLab\__init__.py to __init__.cpython-39.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying alphaBetaLab.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying alphaBetaLab.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying alphaBetaLab.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying alphaBetaLab.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying alphaBetaLab.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
removing 'build\bdist.win-amd64\egg' (and everything under it)
Removing d:\programas\entornos\general\lib\site-packages\alphaBetaLab-1.1.0-py3.9.egg
Copying alphaBetaLab-1.1.0-py3.9.egg to d:\programas\entornos\general\lib\site-packages
```

Finally, when I run an example like the next one:

```
import numpy as np
from alphaBetaLab.abOptionManager import abOptions
from alphaBetaLab.abEstimateAndSave import triMeshSpecFromMshFile, abEstimateAndSaveTriangularEtopo1

# Spectral grid
#dirs = np.linspace(0, 2*np.pi, 25)
#nfreq = 25
dirs = np.linspace(0, 2*np.pi, 3)
nfreq = 3
minfrq = .04118
frqfactor = 1.1
freqs = [minfrq*(frqfactor**i) for i in range(1,nfreq + 1)]

# Mesh
gridname = 'ww3'
mshfile = r'D:\Programas\MatLab_codes\Prueba.msh'
triMeshSpec = triMeshSpecFromMshFile(mshfile)

# Bathymetry
etopoFilePath = r'D:\Usuarios\Documentos\ETOPO\ETOPO1_Ice_g_gmt4.grd'

# Output directory
outputDestDir = r'D:\Programas\MatLab_codes'

# Cores in paralel
nParWorker = 2

# Minimum size of the cells
minSizeKm = 5
opt = abOptions(minSizeKm=minSizeKm)

# Computate
abEstimateAndSaveTriangularEtopo1(dirs, freqs, gridname, triMeshSpec, etopoFilePath, outputDestDir, nParWorker)
```

I get this output/error, which is repeated like in a loop: 

```
building the triangular mesh polygons (may take a while ...)
loading etopo1 bathymetry ...
    building neighbor cells cache (can take some time) ...
    initializing parallel environment ..
done

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Programas\Entornos\general\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Programas\Entornos\general\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\Programas\Entornos\general\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Programas\Entornos\general\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\Programas\Entornos\general\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\Programas\Entornos\general\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\Programas\Entornos\general\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Usuarios\Documentos\Google Drive\Documentos\Ofertas_empleo\ITC\SEIDII_II\Python\WW3_grid.py", line 39, in <module>
    abEstimateAndSaveTriangularEtopo1(dirs, freqs, gridname, triMeshSpec, etopoFilePath, outputDestDir, nParWorker)
  File "D:\Programas\Entornos\general\lib\site-packages\alphabetalab-1.1.0-py3.9.egg\alphaBetaLab\abEstimateAndSave.py", line 169, in abEstimateAndSaveTriangularEtopo1
  File "D:\Programas\Entornos\general\lib\site-packages\numpy\core\numeric.py", line 204, in ones
    a = empty(shape, dtype, order)
numpy.core._exceptions.MemoryError: Unable to allocate 1.74 GiB for an array with shape (10801, 21601) and data type float64

        building the triangular mesh polygons (may take a while ...)
loading etopo1 bathymetry ...

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Programas\Entornos\general\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Programas\Entornos\general\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\Programas\Entornos\general\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Programas\Entornos\general\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\Programas\Entornos\general\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\Programas\Entornos\general\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\Programas\Entornos\general\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Usuarios\Documentos\Google Drive\Documentos\Ofertas_empleo\ITC\SEIDII_II\Python\WW3_grid.py", line 39, in <module>
    abEstimateAndSaveTriangularEtopo1(dirs, freqs, gridname, triMeshSpec, etopoFilePath, outputDestDir, nParWorker)
  File "D:\Programas\Entornos\general\lib\site-packages\alphabetalab-1.1.0-py3.9.egg\alphaBetaLab\abEstimateAndSave.py", line 171, in abEstimateAndSaveTriangularEtopo1
  File "D:\Programas\Entornos\general\lib\site-packages\alphabetalab-1.1.0-py3.9.egg\alphaBetaLab\abHighResAlphaMatrix.py", line 21, in __init__
numpy.core._exceptions.MemoryError: Unable to allocate 1.74 GiB for an array with shape (10801, 21601) and data type float64

        building the triangular mesh polygons (may take a while ...)
loading etopo1 bathymetry ...
```

I have installed: 
numpy 1.21.5
shapely 1.8
matplotlib 3.5.1
basemap 1.3
netCDF4 1.5.8
scipy 1.7.3
proj 8.2.0
pyproj 3.3.0
Python 3.9.7

I have not proj4 installed, but I guess that proj and pyproj should do the work.

**Comment by Jbarrers9740** [comment]
I solved this issue by creating a new environment and manually installing every required library, including proj4=5.2.0. It may sound strange, but for this process, avoiding conda-forge installations (except for proj4) worked much better for me. Even in this case, I still have problems when running the test program, but the example codes seem to work properly. In fact, I created my obstruction files for a real case in WW3. 

Another problem that I found is that, in order to get the aforementioned obstruction files, I had to fix the nParWorker to 1.
